### POST request to create a profile
POST http://localhost:4000/createprofile
Content-Type: application/json

{
  "name": "kumar",
  "age": 28,
  "location": "London",
  "profession": "Software Developer"
}

###

GET http://localhost:4000/profiles